lidofinance/ethereum-validators-monitoring

- src/modules/lighthouse/Eth2Client.ts
- src/modules/lighthouse/errors/BeaconChainGeneralApiError.ts
Now we will not try to re-fetch block info if it is missed
> Don't use fallback for missed blocks

- src/modules/alertmanager/alerts/CriticalMissedProposes.ts
Before: alert every 6h
After: alert every 6h if NO has new missed proposes
> fix: send alert if NO has new missed proposes

- docker/grafana/provisioning/dashboards/operators.json
- docker/prometheus/alerts_rules.test
- docker/prometheus/alerts_rules.yml
Since average inc. delay is not a relevant metric for alerting, we need to look at high inc. delay for N epochs in a row
> feat: change high inc. delay alert

- .github/workflows/ci-dev-new.yml
- .github/workflows/ci-prod-new.yml
- .github/workflows/ci-staging-new.yml
- .github/workflows/create-tag-and-trigger-deploy-new.yml
Separate workflows for new role in infra
> chore: separate workflows for 4.x.x candidate

- docker/alertmanager/alertmanager.yml
- docker/alertmanager/templates/telegram.tmpl
- docker/prometheus/alerts_rules.test
- docker/prometheus/alerts_rules.yml
> feat: support telegram alerts

- docker-compose.yml
- docker/prometheus/alerts_rules.test
- docker/prometheus/alerts_rules.yml
Additional meta-info in discord alerts
> feat: add footer to discord alerts

- docker/prometheus/alerts_rules.test
- docker/prometheus/alerts_rules.yml
- docker/prometheus/fires.yml
- docker/prometheus/prometheus.yml
> feat: add fires count to alerts footer

- .env.example
BREAKING CHANGES: Summary table. Related refactoring
> chore: breaking changes trigger

- package.json
- src/app/app.service.ts
- src/common/config/env.validation.ts
- src/common/eth-providers/consensus-provider/consensus-provider.service.ts
- src/common/prometheus/prometheus.service.ts
- src/duty/attestation/attestation.service.ts
- src/duty/sync/sync.service.ts
- src/inspector/inspector.service.ts
- src/storage/clickhouse/clickhouse.service.ts
- test/duties.e2e-spec.ts
- yarn.lock
- `destroy` for streams
- update ssz lib
- change `check` cycle in attestation duty task
> Performance improvements

- package.json
- src/storage/clickhouse/clickhouse.constants.ts
- src/storage/clickhouse/clickhouse.service.ts
- test/duties.e2e-spec.ts
- yarn.lock
Current unofficial lib makes some troubles while develop (like performance issues, ugly inserts and logging and etc.)
I propose to use [**official** clickhouse](https://clickhouse.com/docs/en/integrations/language-clients/nodejs/) lib.
- Better performance than the current lib
- More flexible and user-friendly use interface
- Reliable support for all versions of clickhouse
- Long-term support
> Use @clickhouse/client

- src/common/eth-providers/consensus-provider/consensus-provider.service.ts
This reverts commit cda84303ca22a232e46a2a19df46fc3d5da03908.
> Revert "fix: long finality or unsynced node case (#92)"

- src/duty/duty.service.ts
- src/duty/state/state.service.ts
- src/duty/summary/summary.service.ts
- src/inspector/inspector.service.ts
- src/storage/clickhouse/clickhouse.service.ts
- test/duties.e2e-spec.ts
Writing to DB in the same state processing stream is too slow. We can separate these two process
> feat: speed up writing to DB

- docker/grafana/provisioning/dashboards/rewards.json
- src/duty/duty.rewards.ts
- src/duty/summary/summary.metrics.ts
- src/inspector/inspector.service.ts
This PR is mostly about improvement processing of finalization in different cases
> chore: minor improvements

- src/duty/attestation/attestation.rewards.ts
- src/duty/duty.service.ts
- src/duty/state/state.service.ts
Batch processing of long loops
> fix: long loops

- src/duty/attestation/attestation.rewards.ts
- src/duty/duty.service.ts
- src/duty/state/state.service.ts
This reverts commit 39ea77f465b4f84bd6b18bd60569d6ee0fcb8771.
> Revert "fix: long loops"

- src/common/eth-providers/consensus-provider/consensus-provider.service.ts
We consider using the last 404 error on BlockInfo requests when a mismatched error between fallbacks
> feat: throw last error

- .env.example
Coming from a standpoint of someone who was completely new to this project, these are changes that would've made my life (and I hope other newcomings) a bit easier.
* changed DB_NAME to default as that is the default when creating a ClickHouse database
* fixed a typo (as discussed with vgorkavenko)
> clarify comments and defaults

- docker/grafana/provisioning/dashboards/operators.json
- docker/grafana/provisioning/dashboards/validators.json
1. Replace protocol from "https" to "http" in links to localhost.
2. Replace links to "goerli.beaconcha.in" with "beaconcha.in".
> fix: incorrect links in dashboards

- src/common/consensus-provider/consensus-provider.service.ts
Reverts lidofinance/ethereum-validators-monitoring#234
> Revert "fix: retry on non finalized epoch"

- .github/workflows/ci-dev.yml
[SRE-2464](https://linear.app/lidofi/issue/SRE-2464)
[infra-mainnet PR](https://github.com/lidofinance/infra-mainnet/pull/6148)
> Workflows adjustments for hoodi/holesky deployments

- docker/grafana/provisioning/dashboards/rewards.json
Remove unnecessary variables from the "Rewards & Penalties" dashboard.
> refactor: rewards dashboard

- docker/prometheus/alerts_rules.test
- docker/prometheus/alerts_rules.yml
Fix grammar issues in alert labels and clarify text.
> fix: grammar issues in alert labels

- docker/grafana/provisioning/dashboards/operators.json
- docker/grafana/provisioning/dashboards/validators.json
- docker/prometheus/alerts_rules.test
- docker/prometheus/alerts_rules.yml
- Fix time ranges in alertmanager tests
- Minor changes in Grafana dashboard namings
> fix: minor fixes in alertmanager tests and Grafana dashboards

- Dockerfile
Update Node.js in the project to 20.x
> chore: update Node.js
