lidofinance/ethereum-validators-monitoring

- src/inspector/processing/data-processing.service.ts
- src/storage/clickhouse/clickhouse.types.ts
Because of the long finality, source may not equal prev epoch from attestation slot. We must take source epoch from attestation (`source.epoch`) and check its root
> fix: check attestation source and target

- src/common/eth-providers/consensus-provider/block-cache/block-cache.service.ts
- src/inspector/inspector.module.ts
- src/inspector/inspector.service.ts
In some cases when node balancer gives us non-finalized responses, we throw error, but don't clear block info cache
> fix: bad cache

- src/common/alertmanager/alerts/BasicAlert.ts
- src/common/alertmanager/alerts/CriticalMissedAttestations.ts
- src/common/alertmanager/alerts/CriticalMissedProposes.ts
- src/common/alertmanager/alerts/CriticalNegativeDelta.ts
- src/common/alertmanager/alerts/CriticalSlashing.ts
- src/common/alertmanager/critical-alerts.module.ts
- src/common/alertmanager/critical-alerts.service.ts
- src/common/prometheus/prometheus.constants.ts
- src/common/prometheus/prometheus.service.ts
- src/duty/attestation/attestation.metrics.ts
- src/duty/propose/propose.metrics.ts
- src/duty/state/state.metrics.ts
- src/duty/sync/sync.metrics.ts
- src/storage/clickhouse/clickhouse.constants.ts
- src/storage/clickhouse/clickhouse.service.ts
- src/storage/clickhouse/clickhouse.types.ts
We should aggregate values by `id` instead of `name` and add new metric `user_operators_identifies` that should help to match operator's name with his `id` for something (eg. alerting)
> fix: case when operator changes his name

- src/common/config/env.validation.ts
- src/duty/duty.service.ts
- src/storage/clickhouse/clickhouse.service.ts
- test/duties.e2e-spec.ts
Broken pipe error are happened very frequently on infra instance. Error is not reproduced locally, but I assume it is due to a buffer overflow. The old approach should bring a soft and safe data insertion
> fix: revert old approach and insert data in chunks

- docker/grafana/provisioning/dashboards/operators.json
- docker/grafana/provisioning/dashboards/validators.json
- src/duty/duty.metrics.ts
- src/duty/duty.service.ts
- src/duty/summary/summary.metrics.ts
- src/inspector/inspector.service.ts
- src/storage/clickhouse/clickhouse.constants.ts
- src/storage/clickhouse/clickhouse.service.ts
- src/storage/clickhouse/clickhouse.types.ts
- src/storage/clickhouse/migrations/migration_000002_rewards.ts
- src/storage/clickhouse/migrations/migration_000004_epoch_processing.ts
In some cases where work of application may have been stopped (redeploy or some exceptional case), we can't be sure that two major tasks (saving data and calculating metrics) have been finished successfully.
To handle this, I propose these:
- add logic to complete of incomplete epoch processing
- add deduplication strategy to queries
> feat: safe epoch processing

- src/common/eth-providers/consensus-provider/consensus-provider.service.ts
Now we check `finalized` block via slot timestamp instead time when slot was fetched
> fix: long finality or unsynced node case

- .env.example
* clarify comments and defaults
* changed DB_NAME to default as that is the default when creating a ClickHouse database
* fixed a typo
* remove leading space from DB_NAME
* improve comment regarding finding a relevant epoch
* use 8123 (http) instead of 8443 (https) as it makes more sense for a local clickhouse instance
---------
> clarify comments and defaults (#186)

- src/common/config/env.validation.ts
As the Altair epoch is different in different testnets, it is not possible to set a static pre-defined number of the `START_EPOCH` as a required minimum value of this variable. So, for now, we skip the validation of this env variable on testnets.
Later it would be better to implement a custom validation directive for validating the minimum possible value of the `START_EPOCH` variable depending on the testnet where the application is running.
> fix: skip validation of `START_EPOCH` env variable

- docker-compose.yml
Pull Request #202 introduced a bug with port variables substitution in the `docker-compose.yml` file. Because of this bug clickhouse was not running correctly in a docker container. Now this bug is fixed.
> fix: incorrect ports in `docker-compose`

- package.json
Temporarily increase the `max-old-space-size` param to 8192 to test Holesky deployment.
> fix: temporarily increase space size

- .env.example
Add empty lines between different sections of the sample `.env` file to improve its readability.
> chore: empty lines in sample env file

- docker/grafana/provisioning/dashboards/rewards.json
Previously the "Earned" parameter in the "Total summary" table of the "Rewards & Penalties" dashboard was calculated incorrectly. It was calculated as `rewards + penalty`, but actually it should be `rewards - penalty`. Now this bug is fixed and the "Earned" column displays correct values.
> fix: incorrect calculation in "Earned" column

- src/common/consensus-provider/consensus-provider.service.ts
Use fallback if the processing state epoch is greater than or equal to the latest epoch returned by the CL node.
> fix: retry on non-finalized epoch

- README.md
- src/app/app.service.ts
- src/common/config/env.validation.ts
- src/common/config/interfaces/environment.interface.ts
- src/duty/attestation/attestation.constants.ts
- src/duty/attestation/attestation.service.ts
Add support for the new attestation logic introduced in the EIP-7045
which is a part of the Dencun hard fork spec.
The only part of the Dencun hard fork that affects E-V-M is the EIP-7045. Here is an exact change that should be supported:
https://github.com/ethereum/consensus-specs/blob/bf09b9a7c4a7b311e86823235815daf31b117574/specs/deneb/beacon-chain.md#modified-get_attestation_participation_flag_indices
Other improvements listed in the Dencun spec don't affect E-V-M.
Now the `attestation_inclusion_delay` is ignored for slots after the Dencun hard fork epoch. For slots before the Dencun hard fork epoch the app works as previously (i. e. checks that the `attestation_inclusion_delay` is not greater than 32).
The Dencun hard fork epoch is predefined for the officially supported networks …
> feat: support Dencun hard fork

- README.md
Add info about how to update the Clickhouse data retention policy on Holesky.
> docs: update info about data retention

- README.md
- src/common/config/env.validation.ts
Remove the Kintsugi network from the list of officially supported chains.
As this network has been officially deprecated and Lido protocol isn't deployed there, it has been decided to remove this network from the list of officially supported chains.
> chore!: remove Kintsugi network

- src/common/consensus-provider/consensus-provider.service.ts
Log an error if the node returns a slot that is less than the last finalized slot in the chain.
Add slot number to the error message that indicates that the last slot hasn't changed for a long time.
> chore: add error logging in case of wrong slot

- src/common/config/env.validation.ts
Set the correct epoch for Dencun hardfork on Mainnet
https://blog.ethereum.org/2024/02/27/dencun-mainnet-announcement
> fix: set correct Dencun Mainnet epoch

- src/app/app.module.ts
- src/app/app.service.ts
- src/common/consensus-provider/consensus-provider.service.ts
- src/common/consensus-provider/intefaces/response.interface.ts
- src/duty/duty.metrics.ts
- src/duty/duty.rewards.ts
- src/validators-registry/keysapi-source/keysapi-source.service.ts
Check that the block returned by the node for the given block ID is finalized and, if not, use the fallback node.
Fix some lint errors.
> chore: add slot finality checking

- src/inspector/inspector.service.ts
Log latest block number received from the node and chosen epoch and slot in the debug logging mode.
> chore: log latest block number from the node

- README.md
Update rules when the `CriticalNegativeDelta` and `CriticalMissedAttestations` alerts are triggered in README.
> fix: update alert rules in README

- docker-compose.yml
When the app is launched in docker containers, it is periodically killed by OOM because 3 GB of memory allocated to the app container is not enough. Now the amount of memory is increased to 5 GB.
> fix: add more memory to app container

- src/common/alertmanager/alerts/CriticalMissedProposes.ts
Due to incorrect conditions for the `CriticalMissedProposes` alert triggering, the alert was not fired if this alert had never been triggered previously. Now this bug is fixed.
> fix: bug in Critical Missed Proposes alert

- README.md
- package.json
- src/app/app.service.ts
- src/common/config/env.validation.ts
- src/common/consensus-provider/consensus-provider.service.ts
- src/common/consensus-provider/intefaces/response.interface.ts
- src/common/functions/makeDefaultMap.ts
- src/duty/attestation/attestation.constants.ts
- src/duty/attestation/attestation.service.ts
- yarn.lock
Implement a prototype of the new algorithm for attestation calculation to support the new attestation data format introduced in the EIP-7549 that will be added to the next Pectra hardfork.
Some useful links that illustrate new data format and calculation rules
- https://eips.ethereum.org/EIPS/eip-7549
- https://github.com/ethereum/consensus-specs/blob/2c1f677187e6534aec77057a7d1cc746a40d3630/specs/electra/beacon-chain.md#attestation
- https://github.com/ethereum/consensus-specs/blob/2c1f677187e6534aec77057a7d1cc746a40d3630/specs/electra/beacon-chain.md#get_committee_indices
- https://github.com/ethereum/consensus-specs/blob/2c1f677187e6534aec77057a7d1cc746a40d3630/specs/electra/beacon-chain.md#modified-get_attesting_indices
**Open questions:**
What to do if the `committee` in the …
> feat: new attestations calculation algorithm

- src/duty/attestation/attestation.rewards.ts
The current calculation algorithm of missed rewards for attestations is working incorrectly for validators with a max effective balance greater than 32. As a result of this calculation, the value of the missed attestation reward for such validators might be negative. The attempt to store a negative value of missed attestation reward to the DB causes failures that lead to a complete inability to update the "validators_summary" table and loss of data about all validators in the epoch where this calculation error happened.
The calculation of missed attestation rewards for 0x02 validators is temporarily disabled until we understand better how to calculate missed attestation rewards for all types of validators.
> fix: missed rewards for attestations

- src/duty/attestation/attestation.rewards.ts
Proper fix for missed attestations rewards calculation.
In the previous version of the missed rewards calculation algorithm, there was a hard assumption that the effective balance of any validator must be 32 ETH. After Pectra hardfork this assumption is no longer valid. So, now to calculate the "perfect" attestation rewards that a validator could earn if it fully executes all attestation duties the algorithm should use the actual validator effective balance, not 32.
This PR makes the rewards calculation algorithm use the actual validator balance in missed rewards calculation and also extracts some common multiplications to new variables.
> fix: missed rewards for attestations - 2

- src/common/consensus-provider/consensus-provider.service.ts
- src/storage/clickhouse/clickhouse.constants.ts
Exclude validators with the "pending_initialized" status from the reward calculation.
There was an error with the reward calculation for some validators on Hoodi testnet on the epoch when the Pectra hardfork was activated (2048).
At the time of the hadrfork, many validators of the "Attestant (BVI) Limited" node operator were waiting for the activation. Most of these validators had the status "pending_queued" at the last epoch before the hardfork (2047). All validators with this status had 32 ETH on their balance. On the epoch 2048 (Pectra hardfork activation epoch), some of these validators changed their status from "pending_queued" to "pending_initialized" (for example, validators with indexes from 1073611 to 1074310) and their balance became zero.
To calculate reward calculation error …
> fix: exclude pending initialized validators

- src/common/consensus-provider/consensus-provider.service.ts
- src/common/functions/retrier.ts
- src/validators-registry/keysapi-source/keysapi-source.client.ts
When `LOG_FORMAT` is set to "simple", the `logger.warn(error)` command logs only the non-default keys of the error object, but not the error message itself. So, in the "simple" log format it is hard to notice an important warning log, and merely impossible to determine the root cause of the error by looking only at the log message.
Now when the app needs to log an error object, the log with the "warning" level always logs the error message of this error object.
> fix: better warnings in logs

- package.json
- yarn.lock
Update "@lodestar/types" library to the most recent version to make EVM work with the Fusaka hardfork.
> fix: update lodestar types
